development:
  sessions:
    default:
      database: wiyomi_development
      hosts:
        - localhost:27017
      options:
  options:
    use_utc: true

production:
  sessions:
    default:
      database: wiyomi_development
      hosts:
        - localhost:27017
      options:
  options:
    use_utc: true

test:
  sessions:
    default:
      database: wiyomi_test
      hosts:
        - localhost:27017
      options:
        read: primary
        max_retries: 1
        retry_interval: 0
